backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "news"
    label: "Nouvelle / evenement de hostaplast"
    files:
      - label: "Nouvelle / evenement de hostaplast"
        name: "news"
        file: "content/news.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Short description",
              name: "shortdescription",
              widget: "text",
            }
          - { label: "Thumbnail", name: "thumbnail", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

  - name: "generalinfo"
    label: "Information general"
    files:
      - label: "Les metadata du website"
        name: "metadata"
        file: "content/metadata.md"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "logo label", name: "logolabel", widget: "string" }
          - {
              label: "Theme color",
              name: "theme",
              widget: "color",
              enableAlpha: true,
              allowInput: true,
            }

      - label: "Notre solution"
        name: "solution"
        file: "content/solution.md"
        fields:
          - { label: "image", name: "image", widget: "image" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

      - label: "À propos de nous"
        name: "aboutus"
        file: "content/aboutus.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Thumbnail", name: "thumbnail", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Nos valeurs"
        name: "values"
        file: "content/value.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Nos fonctionnalités"
        name: "features"
        file: "content/features.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Features"
            name: "features"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "Detail de la solution"
        name: "solution_detail"
        file: "content/solution_details.md"
        fields:
          - { label: "Description", name: "description", widget: "markdown" }
