import Head from "next/head";
import Carousel from "../components/carousel";
import Details from "../components/detail";
import Features from "../components/features";
import LastNews from "../components/last_news";
import Partners from "../components/partners";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <Details />
      <Features />
      <LastNews />
      <Partners />
    </div>
  );
}
